### ISSUE TITLE
404 for github.com/jteeuwen/framebuffer

### ISSUE THREAD

**Issue by mewmew** [gen2brain/goiv#1]
```
u@x220 ~> go get -u -v github.com/gen2brain/goiv/...
github.com/gen2brain/goiv (download)
github.com/BurntSushi/xgb (download)
github.com/BurntSushi/xgbutil (download)
github.com/BurntSushi/freetype-go (download)
github.com/BurntSushi/graphics-go (download)
github.com/NeowayLabs/drm (download)
github.com/blezek/tga (download)
github.com/edsrzf/mmap-go (download)
github.com/hotei/bmp (download)
github.com/jbuchbinder/gopnm (download)
github.com/jteeuwen/framebuffer (download)
# cd .; git clone https://github.com/jteeuwen/framebuffer /home/u/goget/src/github.com/jteeuwen/framebuffer
Cloning into '/home/u/goget/src/github.com/jteeuwen/framebuffer'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/jteeuwen/framebuffer: exit status 128
```

Seems like the https://github.com/jteeuwen/framebuffer repo has been removed, as used by https://github.com/gen2brain/goiv/blob/master/goiv_fb.go

Care to upload a fork if you still have it locally?

Cheers
/u

**Comment by gen2brain** [comment]
Thanks for letting me know. I saw the post about go-bindata but didn't realized framebuffer is from same user. Addressed in https://github.com/gen2brain/goiv/commit/0ac22cba18ec78db1ad3081be0e4eafc21e5b554 , forked repo is here https://github.com/gen2brain/framebuffer .

**Comment by mewmew** [comment]
Thanks for the very quick response! Works now like a charm!
