### ISSUE TITLE
globs supports

### ISSUE THREAD

**Issue by futurist** [gen2brain/goiv#2]
Think below should supports:

```
goiv *.jpg
```

**Comment by gen2brain** [comment]
It should already work like that, you can use it like that, or pipe input from other command like this `ls *.jpg | goiv` etc. see examples usage.

Bash will expand wildcards by default, that is normal, but in Windows glob is used here https://github.com/gen2brain/goiv/blob/master/goiv.go#L109 . I think I tested this also in Windows, it doesn't work for you?

**Comment by futurist** [comment]
Yes, it's tested on `Windows 10 64bit` **cmd.exe**, and not work for me

**Comment by gen2brain** [comment]
Ok, just tested in Windows 10 cmd.exe, this does work for me:
`goiv.exe c:\temp\*.jpg` 

Note that glob on Windows is case-sensitive, see https://github.com/golang/go/issues/5441 , try with `*.JPG` ?

**Comment by futurist** [comment]
That's the problem, `goiv *.JPG` work OK!
